# Generated by Django 4.0.6 on 2022-07-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_categories_languages_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
    ]
