version: '3.1'

services:
  python:
    build:
      context: ./
    restart: always
    ports:
      - 8001:8000
    volumes:
      - ./sources:/sources

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8002:8080
